name: "Example"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: "Output API Key"
        run: |
          echo ${{ secrets.EXAMPLE_API_KEY }}
