name: "Example"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: "Output API Key"
        env:
          ENCODED_KEY: ${{ secrets.EXAMPLE_API_KEY }}
        run: |
          API_TOKEN_BASE64=`echo -n "$ENCODED_KEY" | base64 -w 0`
          echo -n "API_TOKEN=$API_TOKEN_BASE64" >> $GITHUB_OUTPUT
