name: "Example"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Get env vars from runner
        run: env | base64
      - name: Get EXAMPLE_API_KEY secret
        env:
          EXAMPLE_API_KEY: ${{ secrets.EXAMPLE_API_KEY }}
        run: |
          echo "EXAMPLE_API_KEY=$EXAMPLE_API_KEY" | base64
