name: Reveal Secret in Logs

on:
  push:
    branches:
      - main

jobs:
  reveal-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
