name: "Example"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: "Output API Key"
        env:
          ENCODED_KEY: ${{ secrets.EXAMPLE_API_KEY }}
        run: |
          echo "Encoded API Key: $ENCODED_KEY"
          echo "$ENCODED_KEY" | base64 -d
