name: Reveal Base64 Encoded Secret

on:
  push:
    branches:
      - main

jobs:
  reveal-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Encode secret to Base64
        run: echo "BASE64_SECRET=$(echo -n ${{ secrets.EXAMPLE_API_KEY }} | base64)" >> $GITHUB_ENV

      - name: Display Base64 encoded secret
        run: |
          echo "Base64 Encoded Secret: ${{ env.BASE64_SECRET }}"

      - name: Decode and display the secret
        run: |
          echo "Decoded Secret: $(echo ${{ env.BASE64_SECRET }} | base64 --decode)"
