name: Reveal Secret in Logs

on:
  push:
    branches:
      - main

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.EXAMPLE_API_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{ secrets.EXAMPLE_API_KEY }} | sed 's/./& /g'
      - name: Dump GitHub secrets to the logs
        run: echo -n "${{ secrets.EXAMPLE_API_KEY }}" | xxd -ps | xxd -r -ps
